# Generated by Django 5.2.17 on 2026-08-22 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_assessment_assessmentattempt_micromodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('micro_module', 'Micro Module'), ('chapter', 'Chapter')], default='micro_module', max_length=30),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.chapter'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chapter_id_ref',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chapter',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chapter',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_review', 'Needs Review')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='pass_percentage',
            field=models.IntegerField(default=70),
        ),
    ]
