# Generated by Django 5.2.17 on 2026-08-22 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('learning', '0003_assessment_assessment_type_assessment_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chapter',
            name='unique_chapter_order_per_module',
        ),
        migrations.RemoveConstraint(
            model_name='learningmodule',
            name='unique_module_order_per_document',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='module',
        ),
        migrations.RemoveField(
            model_name='learningmodule',
            name='document',
        ),
        migrations.AddField(
            model_name='chapter',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='documents.document'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='end_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='source_heading_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='start_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.chapter'),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='end_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='source_heading_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='start_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_review', 'Needs Review')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='learningmodule',
            constraint=models.UniqueConstraint(fields=('chapter', 'order'), name='unique_module_order_per_chapter'),
        ),
    ]
